Lidar_front_end:
   # lidar_topic: /3rgbd/points2
   lidar_topic: /front/points2_in_front
   lidar_type: 4   # 1 for Livox-avia, 3 for Ouster-OS1-64, 4 for Azure Kinect DK
   N_SCANS: 6
   using_raw_point: 1
   point_filter_num: 1
   
r3live_common:
   if_dump_log: 1                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 1        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 1            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   # image_width: 1280
   # image_height: 720
   image_width: 640
   image_height: 360
   # camera_intrinsic:
   #    [607.778, 0.0, 636.636,
   #    0.0,  607.751, 368.102,
   #    0.0, 0.0, 1.0 ] 
   camera_intrinsic:
      [303.85, 0.0, 318.318,
      0.0,  303.85, 184.51,
      0.0, 0.0, 1.0 ] 
   camera_dist_coeffs: [0.527894, -2.78783, 0.000106269, 2.59275e-05, 1.66303]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. form camera-LiDAR calibration.
   camera_ext_R: #actually , camera imu 
         [-0.00061492, 0.00730016, -0.999973,
            -0.999996, -0.00270155, 0.000595212,
            -0.00269713, 0.99997, 0.00730179]
   # camera_ext_t: [0.050166, 0.0474116, -0.0312415] 
   camera_ext_t: [-0.046, -0.028, 0.003] 
   # camera_ext_t: [-0.028, -0.003, -0.046] 

   # Rough extrinsic value, form CAD model, is not correct enough, but can be online calibrated in our datasets.
   # camera_ext_R:
   #    [0, 0, 1,
   #     -1, 0, 0,
   #     0, -1, 0]
   # camera_ext_t: [0,0,0] 
   
r3live_lio:        
   lio_update_point_step: 1   # Point step used for LIO update.  
   max_iteration: 3           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   voxel_downsample_size_surf: 0.3
   filter_size_map: 0.3   
   lidar_ext_R_il: 
       [ -0.00455602, 0.108595, -0.99407, 
                   -0.999958, -0.00837415, 0.00366818, 
                   -0.0079262, 0.994051, 0.108628]
         # [0.00202008, -0.999985, -0.00508471,
         #    0.108542, -0.00483541, 0.99408,
         #    -0.99409, -0.00256003, 0.10853]
   # camera_ext_t: [0.050166, 0.0474116, -0.0312415] 
   lidar_ext_t_il: [-0.051, 0.003, 0.001] 